FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt ./requirements.txt

RUN python -m pip install -r requirements.txt

COPY . .

# Command can be overwritten by providing a different command in the template directly.
CMD ["main.handler"]